package GasStation;
//stacioni

import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Page extends javax.swing.JFrame
{
    private Station station;
    private DefaultListModel<Stock> stockModelList;
    private DefaultListModel<Sale> saleModelList;

    /**
     * Creates new form Page
     */
    public Page()
    {
        initComponents();

        try
        {
            //Models of stock and sale
            stockModelList = new DefaultListModel<>();
            stockUIList.setModel(stockModelList);

            saleModelList = new DefaultListModel<>();
            saleUIList.setModel(saleModelList);

             //Load Data
            station = new Station();
            station.LoadDataFromDB();

            //display stocks in UI
            for(Stock stock : station.stockList)
            {
                stockModelList.addElement(stock);
            }

            //Display sales in UI
            for(Sale sale : station.saleList)
            {
                saleModelList.addElement(sale);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        profitPanel = new javax.swing.JPanel();
        CalculateButton = new javax.swing.JButton();
        stockDieselLabel = new javax.swing.JLabel();
        stockPetrolLabel = new javax.swing.JLabel();
        totalProfitLabel = new javax.swing.JLabel();
        stockGasLabel = new javax.swing.JLabel();
        saleDieselLabel = new javax.swing.JLabel();
        saleGasLabel = new javax.swing.JLabel();
        salePetrolLabel = new javax.swing.JLabel();
        totalValueInTanksLabel = new javax.swing.JLabel();
        tankGasValueLabel = new javax.swing.JLabel();
        tankPetrolValueLabel = new javax.swing.JLabel();
        tankDieselValueLabel = new javax.swing.JLabel();
        stockPanel = new javax.swing.JPanel();
        stockGasTypeComboBox = new javax.swing.JComboBox();
        stockGasTypeLabel = new javax.swing.JLabel();
        stockQuantityLabel = new javax.swing.JLabel();
        stockQuantityTextField = new javax.swing.JTextField();
        stockPriceTextField = new javax.swing.JTextField();
        stockPriceLabel = new javax.swing.JLabel();
        SaveStockButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        stockUIList = new javax.swing.JList();
        stockPersonNameLabel = new javax.swing.JLabel();
        stockPersonTextField = new javax.swing.JTextField();
        stockListLabel = new javax.swing.JLabel();
        salePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        saleUIList = new javax.swing.JList();
        saleQuantityTextField = new javax.swing.JTextField();
        saleGasTypeLabel = new javax.swing.JLabel();
        salePriceTextField = new javax.swing.JTextField();
        saleQuantityLabel = new javax.swing.JLabel();
        saleGasTypeComboBox = new javax.swing.JComboBox();
        salePriceLabel = new javax.swing.JLabel();
        SaveSaleButton = new javax.swing.JButton();
        saleListLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CalculateButton.setText("Kalkuloni");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        stockDieselLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stockDieselLabel.setText("X litra  Diesel jane magazinuar, dhe kane vlere prej X leke, (cmimi mesatar/liter eshte X)");
        stockDieselLabel.setToolTipText("");

        stockPetrolLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stockPetrolLabel.setText("X litra  Petrol jane magazinuar, dhe kane vlere prej X leke, (cmimi mesatar/liter eshte X)");
        stockPetrolLabel.setToolTipText("");

        totalProfitLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalProfitLabel.setText("Fitimi total ehte X leke.");

        stockGasLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stockGasLabel.setText("X litra Gaz jane magazinuar, dhe kane vlere prej X leke, (cmimi mesatar/liter eshte X)");
        stockGasLabel.setToolTipText("");

        saleDieselLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saleDieselLabel.setText("X litra  Diesel jane shitur, dhe kane vlere prej X leke, (cmimi mesatar/liter eshte X)");
        saleDieselLabel.setToolTipText("");

        saleGasLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saleGasLabel.setText("X litra  Gaz jane shitur, dhe kane vlere prej X leke, (cmimi mesatar/liter eshte X)");
        saleGasLabel.setToolTipText("");

        salePetrolLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salePetrolLabel.setText("X litra  Petrol jane shitur, dhe kane vlere prej X leke, (cmimi mesatar/liter eshte X)");
        salePetrolLabel.setToolTipText("");

        totalValueInTanksLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalValueInTanksLabel.setText("Vlera totale ne magazine eshte X.");

        tankGasValueLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tankGasValueLabel.setText("Sasia totale e Gazit ne magazine eshte X litra  dhe vlen X leke.");
        tankGasValueLabel.setToolTipText("");

        tankPetrolValueLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tankPetrolValueLabel.setText("Sasia totale e Petrol ne magazine eshte X litra  dhe vlen X leke.");
        tankPetrolValueLabel.setToolTipText("");

        tankDieselValueLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tankDieselValueLabel.setText("Sasia totale e Diesel ne magazine eshte X litra  dhe vlen X leke.");
        tankDieselValueLabel.setToolTipText("");

        javax.swing.GroupLayout profitPanelLayout = new javax.swing.GroupLayout(profitPanel);
        profitPanel.setLayout(profitPanelLayout);
        profitPanelLayout.setHorizontalGroup(
            profitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profitPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(profitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalValueInTanksLabel)
                    .addComponent(totalProfitLabel)
                    .addGroup(profitPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(profitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tankPetrolValueLabel)
                            .addComponent(tankDieselValueLabel)
                            .addComponent(stockPetrolLabel)
                            .addComponent(stockDieselLabel)
                            .addComponent(stockGasLabel)
                            .addComponent(salePetrolLabel)
                            .addComponent(saleDieselLabel)
                            .addComponent(saleGasLabel)
                            .addGroup(profitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tankGasValueLabel)))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        profitPanelLayout.setVerticalGroup(
            profitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profitPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(totalProfitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockDieselLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockPetrolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockGasLabel)
                .addGap(18, 18, 18)
                .addComponent(saleDieselLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salePetrolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saleGasLabel)
                .addGap(18, 18, 18)
                .addComponent(totalValueInTanksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tankDieselValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tankPetrolValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tankGasValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CalculateButton.getAccessibleContext().setAccessibleName("CalculateButton");

        tabbedPane.addTab("Fitimet", profitPanel);

        stockGasTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diesel", "Petrol", "Gas", "Other" }));

        stockGasTypeLabel.setText("Lloji i gazit");

        stockQuantityLabel.setText("Sasia");

        stockQuantityTextField.setText("1.00");
        stockQuantityTextField.setToolTipText("");

        stockPriceTextField.setText("1.00");

        stockPriceLabel.setText("Cmimi/liter");
        stockPriceLabel.setToolTipText("");

        SaveStockButton.setText("Ruaj furnizmin");
        SaveStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveStockButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(stockUIList);

        stockPersonNameLabel.setText("Furnizuesi");
        stockPersonNameLabel.setToolTipText("");

        stockListLabel.setText("Lista e magazines");
        stockListLabel.setToolTipText("");

        javax.swing.GroupLayout stockPanelLayout = new javax.swing.GroupLayout(stockPanel);
        stockPanel.setLayout(stockPanelLayout);
        stockPanelLayout.setHorizontalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockGasTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockGasTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockQuantityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stockPriceTextField)
                    .addComponent(stockPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stockPanelLayout.createSequentialGroup()
                        .addComponent(stockPersonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaveStockButton))
                    .addComponent(stockPersonNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addComponent(stockListLabel)
                .addGap(0, 692, Short.MAX_VALUE))
        );
        stockPanelLayout.setVerticalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockGasTypeLabel)
                    .addComponent(stockQuantityLabel)
                    .addComponent(stockPriceLabel)
                    .addComponent(stockPersonNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockGasTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveStockButton)
                    .addComponent(stockPersonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Magazina", stockPanel);

        saleUIList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(saleUIList);

        saleQuantityTextField.setText("1.00");
        saleQuantityTextField.setToolTipText("");

        saleGasTypeLabel.setText("Lloji i gazit");

        salePriceTextField.setText("1.00");

        saleQuantityLabel.setText("Sasia");

        saleGasTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diesel", "Petrol", "Gas", "Other" }));

        salePriceLabel.setText("Cmimi/liter");

        SaveSaleButton.setText("Ruaj Shitjen");
        SaveSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveSaleButtonActionPerformed(evt);
            }
        });

        saleListLabel.setText("Lista e shitjeve");

        javax.swing.GroupLayout salePanelLayout = new javax.swing.GroupLayout(salePanel);
        salePanel.setLayout(salePanelLayout);
        salePanelLayout.setHorizontalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(salePanelLayout.createSequentialGroup()
                                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saleGasTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saleGasTypeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(saleQuantityTextField)
                                    .addComponent(saleQuantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salePriceLabel)
                                    .addGroup(salePanelLayout.createSequentialGroup()
                                        .addComponent(salePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(SaveSaleButton))))
                            .addComponent(saleListLabel))
                        .addGap(0, 389, Short.MAX_VALUE)))
                .addContainerGap())
        );
        salePanelLayout.setVerticalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleGasTypeLabel)
                    .addComponent(saleQuantityLabel)
                    .addComponent(salePriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleGasTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveSaleButton))
                .addGap(18, 18, 18)
                .addComponent(saleListLabel)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Shitjet", salePanel);
        tabbedPane.addTab("Gazet", jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        tabbedPane.getAccessibleContext().setAccessibleName("Tabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed

        //Stock information
        double stockTotalQuantityForDiesel = station.GetTotalQuantityOfGasStock(Station.Diesel);
        double stockAmountOfMoneyForDiesel = station.GetAmountOfMoneyFromStock(Station.Diesel);
        double stockAveragePriceForDiesel = 0;

        if(stockTotalQuantityForDiesel>0)
        {
            stockAveragePriceForDiesel=stockAmountOfMoneyForDiesel/stockTotalQuantityForDiesel;
        }
        stockDieselLabel.setText(" "+stockTotalQuantityForDiesel+" litra  Diesel jane magazinuar, "+
            " dhe vlejne leke"+stockAmountOfMoneyForDiesel+" (leke), "+
            " (cmimi mesatar per liter "+stockAveragePriceForDiesel+")");

        double stockTotalQuantityForPetrol = station.GetTotalQuantityOfGasStock(Station.Petrol);
        double stockAmountOfMoneyForPetrol = station.GetAmountOfMoneyFromStock(Station.Petrol);
        double stockAveragePriceForPetrol = 0;
        if(stockTotalQuantityForPetrol>0)
        {
            stockAveragePriceForPetrol = stockAmountOfMoneyForPetrol/stockTotalQuantityForPetrol;
        }
        stockPetrolLabel.setText(" "+stockTotalQuantityForPetrol+" litra Petrol jane magazinuar, "+
            " dhe vlejne leke"+stockAmountOfMoneyForPetrol+" (leke), "+
            " (cmimi mesatar per liter "+stockAveragePriceForPetrol+")");

        double stockTotalQuantityForGas = station.GetTotalQuantityOfGasStock(Station.Gas);
        double stockAmountOfMoneyForGas = station.GetAmountOfMoneyFromStock(Station.Gas);
        double stockAveragePriceForGas = 0;

        if(stockTotalQuantityForGas>0)
        {
            stockAveragePriceForGas = stockAmountOfMoneyForGas/stockTotalQuantityForGas;
        }
        stockGasLabel.setText(" "+stockTotalQuantityForGas+" litra Gaz jane magazinuar,  "+
            " dhe vlejne leke "+stockAmountOfMoneyForGas+" (leke), "+
            "(cmimi mesatar per liter "+stockAveragePriceForGas+")");

        //Sale Information
        double salesQuantityForDiesel = station.GetTotalQuantityOfGasSales(Station.Diesel);
        double saleAmountOfMoneyForDiesel = station.GetAmountOfMoneyFromSales(Station.Diesel);
        double saleAveragePriceForDiesel = 0;
        if(salesQuantityForDiesel>0)
        {
            saleAveragePriceForDiesel = saleAmountOfMoneyForDiesel/salesQuantityForDiesel;
        }
        saleDieselLabel.setText(" "+ salesQuantityForDiesel +" litra Diesel jane shitur, "+
            " dhe vlejne " +saleAmountOfMoneyForDiesel+" (leke) "+
            "(cmimi mesatar per liter "+saleAveragePriceForDiesel+")");

        double salesQuantityForPetrol = station.GetTotalQuantityOfGasSales(Station.Petrol);
        double saleAmountOfMoneyForPetrol = station.GetAmountOfMoneyFromSales(Station.Petrol);
        double saleAveragePriceForPetrol = 0;
        if(salesQuantityForPetrol>0)
        {
            saleAveragePriceForPetrol = saleAmountOfMoneyForPetrol/salesQuantityForPetrol;
        }
        salePetrolLabel.setText(" "+ salesQuantityForPetrol +" litra Petrol jane shitur, "+
            " dhe vlejne" +saleAmountOfMoneyForPetrol+" (leke) "+
            "(cmimi mesatar per liter "+saleAveragePriceForPetrol+")");

        double salesQuantityForGas = station.GetTotalQuantityOfGasSales(Station.Gas);
        double saleAmountOfMoneyForGas = station.GetAmountOfMoneyFromSales(Station.Gas);
        double saleAveragePriceForGas = 0;
        if(salesQuantityForGas>0)
        {
            saleAveragePriceForGas = saleAmountOfMoneyForGas/salesQuantityForGas;
        }
        saleGasLabel.setText(" "+ salesQuantityForGas +" litra Gas jane shitur, "+
            " dhe vlejne" +saleAmountOfMoneyForGas+" (leke) "+
            "(cmimi mesatar per liter "+saleAveragePriceForGas+")");

        //Tank information
        double tankDieselQuantity = station.gasTanks[Station.Diesel].getActualQuantity();
        double tankDieselValue = tankDieselQuantity*stockAveragePriceForDiesel;
        tankDieselValueLabel.setText("Sasia totale e Diesel ne magazine eshte "+tankDieselQuantity+" litra, "+
            " dhe ka vlere prej "+ tankDieselValue+" (leke)");

        double tankPetrolQuantity = station.gasTanks[Station.Petrol].getActualQuantity();
        double tankPetrolValue = tankPetrolQuantity*stockAveragePriceForPetrol;
        tankPetrolValueLabel.setText("Sasia totale e Petrol ne magazine eshte "+tankPetrolQuantity+" litra, "+
            " dhe ka vlere pre"+tankPetrolValue + " (leke)");

        double tankGasQuantity = station.gasTanks[Station.Gas].getActualQuantity();
        double tanGasValue = tankGasQuantity*stockAveragePriceForGas;
        tankGasValueLabel.setText("Sasia totale e Gazit ne magazine eshte "+tankGasQuantity+" litra, "+
            " dhe ka vlere prej"+tanGasValue+" (leke)");

        //Profit Information
        double dieselProfit = saleAmountOfMoneyForDiesel - salesQuantityForDiesel * stockAveragePriceForDiesel;
        double petrolProfit = saleAmountOfMoneyForPetrol - salesQuantityForPetrol * stockAveragePriceForPetrol;
        double gasProfit = saleAmountOfMoneyForGas - salesQuantityForGas * stockAveragePriceForGas;
        double totalProfit = dieselProfit+petrolProfit+gasProfit;


        totalProfitLabel.setText("Fitimi total eshte $"+totalProfit+" (leke)");

        //Total value in all tanks
        double totalValueInTanks = tankDieselValue+tankPetrolValue+tanGasValue;
        totalValueInTanksLabel.setText("Vlera totale e magazines eshte$"+totalValueInTanks+" leke");
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void SaveStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveStockButtonActionPerformed
        try
        {
            Stock stock = new Stock();
            stock.Person = this.stockPersonTextField.getText();
            stock.GasType = this.stockGasTypeComboBox.getSelectedIndex();
            stock.Quantity = Double.parseDouble(this.stockQuantityTextField.getText());
            stock.PricePerLiter = Double.parseDouble(this.stockPriceTextField.getText());
            stock.Date = Calendar.getInstance().getTime();
            Result result = station.PutGasInTank(stock);

            if(result.Success)
                stockModelList.addElement(stock);
            else
                JOptionPane.showMessageDialog(this, result.Reason);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.toString());
        }
    }//GEN-LAST:event_SaveStockButtonActionPerformed

    private void SaveSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveSaleButtonActionPerformed
        try
        {
            Sale sale = new Sale();

            sale.GasType = this.saleGasTypeComboBox.getSelectedIndex();
            sale.Quantity = Double.parseDouble(this.saleQuantityTextField.getText());
            sale.PricePerLiter = Double.parseDouble(this.salePriceTextField.getText());
            sale.Date = Calendar.getInstance().getTime();

            Result result = station.SellGas(sale);

            if(result.Success)
                saleModelList.addElement(sale);
            else
                JOptionPane.showMessageDialog(this, result.Reason);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.toString());
        }
    }//GEN-LAST:event_SaveSaleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JButton SaveSaleButton;
    private javax.swing.JButton SaveStockButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel profitPanel;
    private javax.swing.JLabel saleDieselLabel;
    private javax.swing.JLabel saleGasLabel;
    private javax.swing.JComboBox saleGasTypeComboBox;
    private javax.swing.JLabel saleGasTypeLabel;
    private javax.swing.JLabel saleListLabel;
    private javax.swing.JPanel salePanel;
    private javax.swing.JLabel salePetrolLabel;
    private javax.swing.JLabel salePriceLabel;
    private javax.swing.JTextField salePriceTextField;
    private javax.swing.JLabel saleQuantityLabel;
    private javax.swing.JTextField saleQuantityTextField;
    private javax.swing.JList saleUIList;
    private javax.swing.JLabel stockDieselLabel;
    private javax.swing.JLabel stockGasLabel;
    private javax.swing.JComboBox stockGasTypeComboBox;
    private javax.swing.JLabel stockGasTypeLabel;
    private javax.swing.JLabel stockListLabel;
    private javax.swing.JPanel stockPanel;
    private javax.swing.JLabel stockPersonNameLabel;
    private javax.swing.JTextField stockPersonTextField;
    private javax.swing.JLabel stockPetrolLabel;
    private javax.swing.JLabel stockPriceLabel;
    private javax.swing.JTextField stockPriceTextField;
    private javax.swing.JLabel stockQuantityLabel;
    private javax.swing.JTextField stockQuantityTextField;
    private javax.swing.JList stockUIList;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel tankDieselValueLabel;
    private javax.swing.JLabel tankGasValueLabel;
    private javax.swing.JLabel tankPetrolValueLabel;
    private javax.swing.JLabel totalProfitLabel;
    private javax.swing.JLabel totalValueInTanksLabel;
    // End of variables declaration//GEN-END:variables
}
